/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HQ
 */
public class AdminDeshbord extends javax.swing.JFrame {

    
    private  int Userid ;
   
    /**
     * Creates new form AdminDeshbord
     */
    public AdminDeshbord() {
        initComponents();
    }
    private boolean iskh_;
    public AdminDeshbord(int userid , boolean iskh) {
        initComponents();
          this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.Userid = userid;
        this.iskh_ = iskh;
        setKhmerFont(this);
         if(iskh) {
        iskh = false;
    
                setKh();

    } else {
        iskh = true;    setEng();
    }
              try {
    DashBoardPanel_ dash = new DashBoardPanel_();
                 showPanel(dash);   // បង្ហាញ window ថ្មី
} catch (Exception ex) {
}
    }
public void setKh() {
    lbladmin.setText("គ្រប់គ្រង");
    btnCustomer.setText("អតិថិជន");
    btnDashboard.setText("ផ្ទាំងគ្រប់គ្រង");
    btnReport.setText("របាយការណ៍");
    btnSitting.setText("ការកំណត់");
    btnTransation.setText("ប្រតិបត្តិការ");
    btnlogout.setText("ចាកចេញ");
      jButton2.setText("English");
    iskh_ = true;
}

public void setEng() {
    lbladmin.setText("Admin");
    btnCustomer.setText("Customer");
    btnDashboard.setText("Dashboard");
    btnReport.setText("Report");
    btnSitting.setText("Setting");
    btnTransation.setText("Transaction");
    btnlogout.setText("Logout");iskh_= false;
      jButton2.setText("ខ្មែរ");
}

private void setKhmerFont(java.awt.Component component) {
    java.awt.Font current = component.getFont();
    java.awt.Font khFont = new java.awt.Font("Khmer OS Battambang", current.getStyle(), current.getSize());
    component.setFont(khFont);

    if (component instanceof java.awt.Container) {
        for (java.awt.Component child : ((java.awt.Container) component).getComponents()) {
            setKhmerFont(child);
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        panel2 = new java.awt.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbladmin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnTransation = new javax.swing.JButton();
        btnSitting = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblLang = new javax.swing.JLabel();
        btnlogout1 = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();

        jMenuItem1.setText("Suspicious");
        jMenuItem1.setToolTipText("Suspicious");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Daily Transation ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("ReportByAccout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem4.setText("HigtTransation");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem4);

        jMenuItem5.setText("CashFlowForm");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        jMenuItem6.setText("PeakHourAnalysis");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem6);

        jMenuItem7.setText("guiMobile_topup");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem7);

        jMenuItem8.setText("CashFlowForm");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem8);

        jMenuItem9.setText("CardList");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem9);

        jMenuItem10.setText("ListAdmin");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel2.setBackground(new java.awt.Color(225, 225, 225));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/software-engineer.png"))); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(0, 102, 204));

        lbladmin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbladmin.setText("ADMIN");

        jPanel1.setBackground(new java.awt.Color(225, 225, 225));

        btnDashboard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDashboard.setText(" Dashboard");
        btnDashboard.setToolTipText("");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnCustomer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCustomer.setText(" Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnTransation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTransation.setText(" Transactions");
        btnTransation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransationActionPerformed(evt);
            }
        });

        btnSitting.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSitting.setText(" Sitting");

        btnReport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReport.setText(" Report");
        btnReport.setComponentPopupMenu(jPopupMenu1);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnlogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnlogout.setText(" Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(10, 31, 57));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(220, 194, 154));
        jButton2.setText("ខ្មែរ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        lblLang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLang.setForeground(new java.awt.Color(220, 194, 154));
        lblLang.setText("Language :");

        btnlogout1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnlogout1.setText("User");
        btnlogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnlogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblLang)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTransation, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSitting, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnDashboard)
                .addGap(16, 16, 16)
                .addComponent(btnCustomer)
                .addGap(16, 16, 16)
                .addComponent(btnTransation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport)
                .addGap(18, 18, 18)
                .addComponent(btnSitting)
                .addGap(18, 18, 18)
                .addComponent(btnlogout1)
                .addGap(16, 16, 16)
                .addComponent(btnlogout)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLang)
                    .addComponent(jButton2))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lbladmin))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbladmin)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1067, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
     try {
    DashBoardPanel_ dash = new DashBoardPanel_();
                 showPanel(dash);   // បង្ហាញ window ថ្មី
} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
}
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
         
          try{
        currentPanel = "Customer";
        guiCustomerManegement desh = new guiCustomerManegement(Userid, iskh_);
        showPanel(desh);
    }catch(Exception ex){
        ex.printStackTrace();
    }
        
   
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnTransationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransationActionPerformed

         try{
        currentPanel = "transaction";
             guiTransationAdmin desh = new guiTransationAdmin();
        showPanel(desh);
    }catch(Exception ex){
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnTransationActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
//        // TODO add your handling code here:​​​ guitrasation
//           try{
//               Report desh = new Report();
//            showPanel(desh);
//        }catch(Exception ex)
//         {
//                ex.printStackTrace();
//                JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
//         }
try {
       
        jPopupMenu1.show(btnReport, 0, btnReport.getHeight());

  
        
    } catch(Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnReportActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       // toggle language value
    iskh_ = !iskh_;

    if(iskh_) {
        setKh();
        jButton2.setText("English");
    } else {
        setEng();
        jButton2.setText("ខ្មែរ");
    }

    reloadCurrentPanel();
    }//GEN-LAST:event_jButton2ActionPerformed
private void reloadCurrentPanel() {

    try{
        switch(currentPanel){

            case "transaction":
                showPanel(new guitrasation(Userid, iskh_));
                break;

            case "report":
                showPanel(new Report());
                break;

            case "dashboard":
                showPanel(new DashBoardPanel_());
                break;

            case "Customer":
                showPanel(new guiCustomerManegement(Userid, iskh_));
                break;
            case "User" : 
                showPanel(new guiCreateUsers(Userid, iskh_));

                break;
            default:
                // nothing opened yet
                break;
        }

    }catch(Exception ex){
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }
}

    private void btnlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout1ActionPerformed
        // TODO add your handling code here:
        //guiCreateUser
           try {
               this.currentPanel = "User";
    guiCreateUsers dash = new guiCreateUsers(Userid , iskh_);
                 showPanel(dash);   
} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
}
    }//GEN-LAST:event_btnlogout1ActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
  int choice = JOptionPane.showConfirmDialog(
        null,
        "Are you sure you want to delete?",
        "Delete",
        JOptionPane.YES_NO_OPTION
);

if (choice == JOptionPane.YES_OPTION) {
    this.dispose();
}

    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        guiSuspicious gui = new guiSuspicious();
    
       gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
          guiReportDaily gui = new guiReportDaily();
    
         gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:guiHigtTransation
                  guiHigtTransation gui = new guiHigtTransation();
           gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
            guiReportByAccout gui = new guiReportByAccout();
           gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:CashFlowForm
          CashFlowForm gui = new CashFlowForm();
           gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
          PeakHourAnalysis gui = new PeakHourAnalysis();
       gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:guiMobile_topup
           guiMobile_topup gui = new guiMobile_topup();

                 gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
            CashFlowForm gui = new CashFlowForm();

             // កំណត់ឱ្យបិទតែ Window មួយនេះ មិនមែនបិទ Project ទាំងមូលទេ
             gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:rptCardList
        
                rptCardList gui = new rptCardList();

             // កំណត់ឱ្យបិទតែ Window មួយនេះ មិនមែនបិទ Project ទាំងមូលទេ
             gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:rptListAdmin
        
             rptListAdmin gui = new rptListAdmin();

             // កំណត់ឱ្យបិទតែ Window មួយនេះ មិនមែនបិទ Project ទាំងមូលទេ
             gui.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

             gui.setLocationRelativeTo(null);
             gui.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDeshbord().setVisible(true);
            }
        });
    }
    private String currentPanel = "";

     private void showPanel(JPanel panel) {
     panel.setSize(jPanelMain.getWidth(), jPanelMain.getHeight());
     panel.setLocation(0, 0);

    jPanelMain.removeAll();
    jPanelMain.setLayout(new BorderLayout());
    jPanelMain.add(panel, BorderLayout.CENTER);
    jPanelMain.revalidate();
    jPanelMain.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSitting;
    private javax.swing.JButton btnTransation;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnlogout1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblLang;
    private javax.swing.JLabel lbladmin;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
