/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author HQ
 */
public class frmGetCash extends javax.swing.JFrame {

    /**
     * Creates new form frmGetCash
     */
    public frmGetCash() {
 
    }  
    public frmGetCash(int userid) {
          initComponents();
        this.currentId = userid;
        setLocationRelativeTo(null);
    }
    private int currentId;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        panel1 = new java.awt.Panel();
        lblTitleGetCash = new java.awt.Label();
        txtAmount = new javax.swing.JTextField();
        btn20 = new java.awt.Button();
        btn40 = new java.awt.Button();
        btn60 = new java.awt.Button();
        btn100 = new java.awt.Button();
        btnGetCash = new java.awt.Button();
        btn62 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        popupMenu2.setLabel("popupMenu2");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(10, 31, 57));
        setSize(new java.awt.Dimension(650, 480));

        panel1.setBackground(new java.awt.Color(10, 31, 57));
        panel1.setPreferredSize(new java.awt.Dimension(400, 600));

        lblTitleGetCash.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblTitleGetCash.setForeground(new java.awt.Color(220, 194, 154));
        lblTitleGetCash.setName(""); // NOI18N
        lblTitleGetCash.setText("GET CASH");

        txtAmount.setBackground(new java.awt.Color(10, 31, 57));
        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(220, 194, 154));
        txtAmount.setName(""); // NOI18N

        btn20.setActionCommand("20");
        btn20.setBackground(new java.awt.Color(10, 31, 57));
        btn20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn20.setForeground(new java.awt.Color(220, 194, 154));
        btn20.setLabel("20 $");
        btn20.setName("20"); // NOI18N
        btn20.setPreferredSize(new java.awt.Dimension(100, 70));
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btn40.setActionCommand("40");
        btn40.setBackground(new java.awt.Color(10, 31, 57));
        btn40.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn40.setForeground(new java.awt.Color(220, 194, 154));
        btn40.setLabel("40 $");
        btn40.setPreferredSize(new java.awt.Dimension(100, 70));
        btn40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn40ActionPerformed(evt);
            }
        });

        btn60.setBackground(new java.awt.Color(10, 31, 57));
        btn60.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn60.setForeground(new java.awt.Color(220, 194, 154));
        btn60.setLabel("60 $");
        btn60.setPreferredSize(new java.awt.Dimension(100, 70));
        btn60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn60ActionPerformed(evt);
            }
        });

        btn100.setBackground(new java.awt.Color(10, 31, 57));
        btn100.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn100.setForeground(new java.awt.Color(220, 194, 154));
        btn100.setLabel("100 $");
        btn100.setPreferredSize(new java.awt.Dimension(100, 70));
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });

        btnGetCash.setBackground(new java.awt.Color(10, 31, 57));
        btnGetCash.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGetCash.setForeground(new java.awt.Color(220, 194, 154));
        btnGetCash.setLabel("Next");
        btnGetCash.setPreferredSize(new java.awt.Dimension(100, 70));
        btnGetCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCashActionPerformed(evt);
            }
        });

        btn62.setBackground(new java.awt.Color(10, 31, 57));
        btn62.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn62.setForeground(new java.awt.Color(220, 194, 154));
        btn62.setLabel("CanCel");
        btn62.setPreferredSize(new java.awt.Dimension(100, 70));
        btn62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn62ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 194, 154));
        jLabel1.setText("Amount");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnGetCash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn60, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn100, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn62, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn40, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn60, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(192, 192, 192))
        );

        btn20.getAccessibleContext().setAccessibleName("20");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        txtAmount.setText(String.valueOf(20));

    }//GEN-LAST:event_btn20ActionPerformed

    private void btnGetCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCashActionPerformed
         String text = txtAmount.getText().trim();

    if (text.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter amount.");
        return;
    }

    double amount;
    try {
        amount = Double.parseDouble(text);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid amount.");
        return;
    }

    if (amount <= 0) {
        JOptionPane.showMessageDialog(this, "Amount must be > 0.");
        return;
    }

    // ✅ Open step 2 form with amount
    guiChooseAccount step2 = new guiChooseAccount(this.currentId, amount);
    step2.setLocationRelativeTo(this);
    step2.setVisible(true);

    this.dispose();  // close step1
    }//GEN-LAST:event_btnGetCashActionPerformed

    private void btn62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn62ActionPerformed
            MainForm main = new MainForm(this.currentId);
            main.setLocationRelativeTo(null);
            main.setVisible(true);

            this.dispose(); 
    }//GEN-LAST:event_btn62ActionPerformed

    private void btn40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn40ActionPerformed
        txtAmount.setText(String.valueOf(40));// TODO add your handling code here:
    }//GEN-LAST:event_btn40ActionPerformed

    private void btn60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn60ActionPerformed
txtAmount.setText(String.valueOf(60));        // TODO add your handling code here:
    }//GEN-LAST:event_btn60ActionPerformed

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
txtAmount.setText(String.valueOf(100));        // TODO add your handling code here:
    }//GEN-LAST:event_btn100ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGetCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGetCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGetCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGetCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGetCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn100;
    private java.awt.Button btn20;
    private java.awt.Button btn40;
    private java.awt.Button btn60;
    private java.awt.Button btn62;
    private java.awt.Button btnGetCash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.Label lblTitleGetCash;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.Panel panel1;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    public javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
