/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

import com.mycompany.atm.transaction.system.DB.DBHelper;
import javax.swing.JOptionPane;

/**
 *
 * @author HQ
 */
public class guiChooseAccount extends javax.swing.JFrame {
    /**
     * Creates new form guiChooseAccount
     */
    
    private int currentUserId;
    private double withdrawAmount;
    
    public guiChooseAccount(int userid , double amount) {
        initComponents();
          this.currentUserId = userid;
        this.withdrawAmount = amount;

        setLocationRelativeTo(null);

        txtAmount.setText(String.format("%,.2f", withdrawAmount));  // show 40.00
        loadAccountsToCombo();   //
    }
   public guiChooseAccount() {
        initComponents();
    }
   private boolean iskh;
   private void loadAccountsToCombo() {
    String sql = """
        SELECT "AccountNo", "AccountType", "Balance($)", "isKh"
        FROM public."CUSTOMER"
        WHERE "UserID" = %d
        """.formatted(currentUserId);

    var list = DBHelper.getValues(sql);
    cboAccount.removeAllItems();

    for (var row : list) {
        String no = row.get("AccountNo").toString();
        String type = row.get("AccountType").toString();
        double bal  = ((Number)row.get("Balance($)")).doubleValue();
         this.iskh = (boolean)row.get("isKh");
        String symbol = this.iskh ? "៛" : "$";

        String text = "%s - %s (%,.2f %s)".formatted(no, type, bal, symbol);
        cboAccount.addItem(text);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGetCash = new java.awt.Button();
        lblAmount = new java.awt.Label();
        lblAmount1 = new java.awt.Label();
        cboAccount = new javax.swing.JComboBox<>();
        txtAmount = new javax.swing.JTextField();
        btnGetCash1 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(640, 480));

        jPanel1.setBackground(new java.awt.Color(10, 31, 57));
        jPanel1.setForeground(new java.awt.Color(220, 194, 154));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 480));

        btnGetCash.setBackground(new java.awt.Color(10, 31, 57));
        btnGetCash.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGetCash.setForeground(new java.awt.Color(220, 194, 154));
        btnGetCash.setLabel("GetCash");
        btnGetCash.setPreferredSize(new java.awt.Dimension(100, 70));
        btnGetCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCashActionPerformed(evt);
            }
        });

        lblAmount.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAmount.setForeground(new java.awt.Color(220, 194, 154));

        lblAmount1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblAmount1.setForeground(new java.awt.Color(220, 194, 154));
        lblAmount1.setText("Amount :");

        cboAccount.setBackground(new java.awt.Color(10, 31, 57));
        cboAccount.setEditable(true);
        cboAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboAccount.setForeground(new java.awt.Color(220, 194, 154));
        cboAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtAmount.setBackground(new java.awt.Color(10, 31, 57));
        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(220, 194, 154));
        txtAmount.setName(""); // NOI18N

        btnGetCash1.setBackground(new java.awt.Color(10, 31, 57));
        btnGetCash1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGetCash1.setForeground(new java.awt.Color(220, 194, 154));
        btnGetCash1.setLabel("Cancel");
        btnGetCash1.setPreferredSize(new java.awt.Dimension(100, 70));
        btnGetCash1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCash1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                            .addComponent(cboAccount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGetCash1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetCash1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCashActionPerformed
   this.iskh = false;
        if (cboAccount.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Please choose account.");
        return;
    } 
     
String item = cboAccount.getSelectedItem().toString();

String[] mainParts = item.split(" - ");

String accountNo = mainParts[0];   

String accountType = mainParts[1];    
 


    String sqlLoad = """
        SELECT "ID", "Balance($)", "isKh", "AccountNo"
        FROM public."CUSTOMER"
        WHERE "UserID" = %d
          AND "AccountNo" = '%s'
        """.formatted(currentUserId, accountNo);

    var list = DBHelper.getValues(sqlLoad);
    if (list.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Account not found.");
        return;
    }

    var row = list.get(0);
    double balance = ((Number)row.get("Balance($)")).doubleValue();
    this.iskh  = (boolean)row.get("isKh");
    String symbol = this.iskh  ? "៛" : "$";

    long accountId = Long.parseLong(row.get("ID").toString());       
   // String accountNo = row.get("AccountNo").toString();
 double withdrawAmountriel = 0;
   if(this.iskh){
       withdrawAmountriel = withdrawAmount *4100;
       if (withdrawAmountriel > balance) {
           JOptionPane.showMessageDialog(this, "Insufficient balance!");
           return;
       }else{
           withdrawAmount = withdrawAmountriel;
       }
   }

    if (withdrawAmount > balance) {
        JOptionPane.showMessageDialog(this, "Insufficient balance!");
        return;
    }
    

    double newBalance = balance - withdrawAmount;


    String sqlUpdate = """
        UPDATE public."CUSTOMER"
        SET "Balance($)" = %f
        WHERE "ID" = %d
        """.formatted(newBalance, accountId);

    String sqlHistory = """
        INSERT INTO public."atm_transaction"
        (account_id, user_id, tran_type, amount, is_kh,
         balance_before, balance_after, note)
        VALUES (%d, %d, '%s', %f, %b, %f, %f, '%s')
        """.formatted(
            accountId,
            currentUserId,
            "GET_CASH",
            withdrawAmount,
            this.iskh ,
            balance,
            newBalance,
            "ATM GET CASH - " + accountNo
        );


    java.sql.Connection con = null;
    java.sql.Statement stmt = null;

    try {
        con = com.mycompany.atm.transaction.system.DB.dbcontextion.getConnection();
        con.setAutoCommit(false);   // start transaction

        stmt = con.createStatement();
        stmt.executeUpdate(sqlUpdate);   // update balance
        stmt.executeUpdate(sqlHistory);  // insert history

        con.commit();   // ✅ success, commit

        JOptionPane.showMessageDialog(this,
            "Withdraw: " + String.format("%,.2f %s", withdrawAmount, symbol)
          + "\nNew Balance: " + String.format("%,.2f %s", newBalance, symbol)
          + "\nTransaction Saved!");

       MainForm main = new MainForm(this.currentUserId);
            main.setLocationRelativeTo(null);
            main.setVisible(true);

            this.dispose(); 
    }
    catch (Exception ex) {
        try {
            if (con != null) con.rollback();   // ❌ error → rollback everything
        } catch (Exception ignore) {}

        JOptionPane.showMessageDialog(this,
            "Error while processing transaction.\nAll changes rolled back.\n" + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    finally {
        try {
            if (stmt != null) stmt.close();
            if (con != null) {
                con.setAutoCommit(true);
                con.close();
            }
        } catch (Exception ignore) {}
    }
    }//GEN-LAST:event_btnGetCashActionPerformed

    private void btnGetCash1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCash1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetCash1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiChooseAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiChooseAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiChooseAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiChooseAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiChooseAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnGetCash;
    private java.awt.Button btnGetCash1;
    private javax.swing.JComboBox<String> cboAccount;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label lblAmount;
    private java.awt.Label lblAmount1;
    public javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
