/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

import com.mycompany.atm.transaction.system.DB.DBHelper;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class guiDeposit extends javax.swing.JFrame {

    /**
     * Creates new form guiDeposit
     */
    private int currentUserId;
    public guiDeposit(){
        
    }
    public guiDeposit(int currentUserId) {
        initComponents(); 
        this.currentUserId = currentUserId;

        this.loadAccountsToCombo();
        
    }
     private boolean iskh;
    private void loadAccountsToCombo() {

    String sql = """
        SELECT a.account_no      AS account_no,
               a.account_type    AS account_type,
               a.balance         AS balance,
               a.is_kh           AS is_kh
        FROM account a
        JOIN public."CUSTOMER" c
             ON a.customer_id = c."ID"
        WHERE c."UserID" = %d
        """.formatted(currentUserId);

    var list = DBHelper.getValues(sql);
    cboAccount.removeAllItems();

    for (var row : list) {
        String no   = row.get("account_no").toString();
        String type = row.get("account_type").toString();
        double bal  = ((Number) row.get("balance")).doubleValue();
        boolean isKh = (Boolean) row.get("is_kh");   // or (boolean)

        String symbol = isKh ? "៛" : "$";
        String text = "%s - %s (%,.2f %s)".formatted(no, type, bal, symbol);

        cboAccount.addItem(text);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitleGetCash = new java.awt.Label();
        txtAmount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboAccount = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btndeposit = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 31, 57));
        jPanel1.setForeground(new java.awt.Color(220, 194, 154));

        lblTitleGetCash.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblTitleGetCash.setForeground(new java.awt.Color(220, 194, 154));
        lblTitleGetCash.setName(""); // NOI18N
        lblTitleGetCash.setText("Deposite");

        txtAmount.setBackground(new java.awt.Color(10, 31, 57));
        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(220, 194, 154));
        txtAmount.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 194, 154));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/salary.png"))); // NOI18N
        jLabel1.setText("Amount");

        cboAccount.setBackground(new java.awt.Color(10, 31, 57));
        cboAccount.setEditable(true);
        cboAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboAccount.setForeground(new java.awt.Color(220, 194, 154));
        cboAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 194, 154));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/passbook.png"))); // NOI18N
        jLabel2.setText("Choose Account");

        btndeposit.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit.setText("Deposit");
        btndeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(21, 42, 66));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(220, 194, 154));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow.png"))); // NOI18N
        jButton5.setText("CanCel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cboAccount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btndeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositActionPerformed
   String txt = txtAmount.getText().trim();
if (txt.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter amount.");
    return;
}

double depositAmount;
try {
    depositAmount = Double.parseDouble(txt);
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Amount invalid.");
    return;
}

if (depositAmount <= 0) {
    JOptionPane.showMessageDialog(this, "Amount must be > 0.");
    return;
}

this.iskh = false;

if (cboAccount.getSelectedItem() == null) {
    JOptionPane.showMessageDialog(this, "Please choose account.");
    return;
}

String item = cboAccount.getSelectedItem().toString();
String[] mainParts = item.split(" - ");
if (mainParts.length < 1) {
    JOptionPane.showMessageDialog(this, "Invalid account format.");
    return;
}

String accountNo = mainParts[0];

String sqlLoad = """
    SELECT a.id, a.balance, a.is_kh, a.account_no
    FROM account a
    JOIN public."CUSTOMER" c ON a.customer_id = c."ID"
    WHERE c."UserID" = %d
      AND a.account_no = '%s'
    """.formatted(currentUserId, accountNo);

var list = DBHelper.getValues(sqlLoad);
if (list.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Account not found.");
    return;
}

var row = list.get(0);
double balance = ((Number) row.get("balance")).doubleValue();
this.iskh = (Boolean) row.get("is_kh");
String symbol = this.iskh ? "៛" : "$";
long accountId = ((Number) row.get("id")).longValue();

String sqlLoadCurrency = """
    SELECT id, from_code, to_code, rate
    FROM public.currency_rate
    WHERE from_code = 'USD'
    ORDER BY effective_at DESC
    LIMIT 1
""";

var listCurrency = DBHelper.getValues(sqlLoadCurrency);

double rateUsd = 0;
if (!listCurrency.isEmpty()) {
    var rowCurrency = listCurrency.get(0);
    rateUsd = ((Number) rowCurrency.get("rate")).doubleValue();
}

double depositAmountForDb = depositAmount;

if (this.iskh) {
    if (rateUsd == 0) {
        JOptionPane.showMessageDialog(this,
            "Currency rate not found. Cannot process deposit.");
        return;
    }
    double depositRiel = depositAmount * rateUsd;
    depositAmountForDb = depositRiel;
}

double newBalance = balance + depositAmountForDb;

String sqlUpdate = """
    UPDATE account
    SET balance = %f
    WHERE id = %d
    """.formatted(newBalance, accountId);

String sqlHistory = """
    INSERT INTO public."atm_transaction"
    (account_id, user_id, tran_type, amount, is_kh,
     balance_before, balance_after, note)
    VALUES (%d, %d, '%s', %f, %b, %f, %f, '%s')
    """.formatted(
        accountId,
        currentUserId,
        "DEPOSIT",
        depositAmountForDb,
        this.iskh,
        balance,
        newBalance,
        "ATM DEPOSIT - " + accountNo
    );

java.sql.Connection con = null;
java.sql.Statement stmt = null;

try {
    con = com.mycompany.atm.transaction.system.DB.dbcontextion.getConnection();
    con.setAutoCommit(false);

    stmt = con.createStatement();
    stmt.executeUpdate(sqlUpdate);
    stmt.executeUpdate(sqlHistory);

    con.commit();

    JOptionPane.showMessageDialog(this,
        "Deposit: " + String.format("%,.2f %s", depositAmountForDb, symbol)
      + "\nNew Balance: " + String.format("%,.2f %s", newBalance, symbol)
      + "\nTransaction Saved!");

    MainForm main = new MainForm(this.currentUserId);
    main.setLocationRelativeTo(null);
    main.setVisible(true);
    this.dispose();

} catch (Exception ex) {
    try {
        if (con != null) con.rollback();
    } catch (Exception ignore) {}

    JOptionPane.showMessageDialog(this,
        "Error while processing deposit.\nAll changes rolled back.\n" + ex.getMessage(),
        "Error",
        JOptionPane.ERROR_MESSAGE);
} finally {
    try {
        if (stmt != null) stmt.close();
        if (con != null) {
            con.setAutoCommit(true);
            con.close();
        }
    } catch (Exception ignore) {}
}

    }//GEN-LAST:event_btndepositActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         MainForm main = new MainForm(this.currentUserId);
            main.setLocationRelativeTo(null);
            main.setVisible(true);

            this.dispose();   
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiDeposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiDeposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeposit;
    private javax.swing.JComboBox<String> cboAccount;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label lblTitleGetCash;
    public javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
