/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

/**
 *
 * @author USER
 */
public class guiPayment extends javax.swing.JFrame {
    
    private int userid;
    /**
     * Creates new form guiPayment
     */
    public guiPayment() {
    
    }
  

    guiPayment(int currentUserId) {
         initComponents();
         this.userid = currentUserId;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        lblTitleGetCash = new java.awt.Label();
        btn64 = new java.awt.Button();
        btndeposit = new javax.swing.JButton();
        btndeposit1 = new javax.swing.JButton();
        btndeposit2 = new javax.swing.JButton();
        btndeposit3 = new javax.swing.JButton();
        btndeposit4 = new javax.swing.JButton();
        btndeposit5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(10, 31, 57));

        lblTitleGetCash.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblTitleGetCash.setForeground(new java.awt.Color(220, 194, 154));
        lblTitleGetCash.setName(""); // NOI18N
        lblTitleGetCash.setText("Payment");

        btn64.setBackground(new java.awt.Color(10, 31, 57));
        btn64.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn64.setForeground(new java.awt.Color(220, 194, 154));
        btn64.setLabel("Back");
        btn64.setPreferredSize(new java.awt.Dimension(100, 70));
        btn64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn64ActionPerformed(evt);
            }
        });

        btndeposit.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit.setText("Deposit");
        btndeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositActionPerformed(evt);
            }
        });

        btndeposit1.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit1.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit1.setText("Deposit");
        btndeposit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeposit1ActionPerformed(evt);
            }
        });

        btndeposit2.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit2.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit2.setText("Phone Tup_up");
        btndeposit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeposit2ActionPerformed(evt);
            }
        });

        btndeposit3.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit3.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit3.setText("Internet");
        btndeposit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeposit3ActionPerformed(evt);
            }
        });

        btndeposit4.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit4.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit4.setText("Back");
        btndeposit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeposit4ActionPerformed(evt);
            }
        });

        btndeposit5.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit5.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit5.setText("Deposit");
        btndeposit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeposit5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn64, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndeposit2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndeposit3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndeposit4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndeposit5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(btndeposit1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btndeposit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndeposit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndeposit2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndeposit3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndeposit4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndeposit5)
                .addGap(250, 250, 250)
                .addComponent(btn64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn64ActionPerformed
    
    }//GEN-LAST:event_btn64ActionPerformed

    private void btndepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositActionPerformed
           guipayelectricity payWaterForm = new guipayelectricity(this.userid);
           payWaterForm.setVisible(true);      
           payWaterForm.setLocationRelativeTo(null);       
    }//GEN-LAST:event_btndepositActionPerformed

    private void btndeposit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeposit1ActionPerformed
               guiPayWater payWaterForm = new guiPayWater(this.userid);
    payWaterForm.setVisible(true);      
    payWaterForm.setLocationRelativeTo(null);
    }//GEN-LAST:event_btndeposit1ActionPerformed

    private void btndeposit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeposit2ActionPerformed
          guipayPhoneTop_up payWaterForm = new guipayPhoneTop_up(this.userid);
            payWaterForm.setVisible(true);      
            payWaterForm.setLocationRelativeTo(null); 
    }//GEN-LAST:event_btndeposit2ActionPerformed

    private void btndeposit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeposit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeposit3ActionPerformed

    private void btndeposit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeposit4ActionPerformed
      MainForm main = new MainForm(this.userid);
            main.setLocationRelativeTo(null);
            main.setVisible(true);

            this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btndeposit4ActionPerformed

    private void btndeposit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeposit5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeposit5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiPayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn64;
    private javax.swing.JButton btndeposit;
    private javax.swing.JButton btndeposit1;
    private javax.swing.JButton btndeposit2;
    private javax.swing.JButton btndeposit3;
    private javax.swing.JButton btndeposit4;
    private javax.swing.JButton btndeposit5;
    private java.awt.Label lblTitleGetCash;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
