/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

import com.mycompany.atm.transaction.system.DB.DBHelper;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class guiPayWater extends javax.swing.JFrame {

  private int userid;
    public guiPayWater() {
        initComponents();
    }
    public guiPayWater(int userid){
        initComponents();
        this.userid = userid;
          this.loadAccountsToCombo();
    }
  
private void loadAccountsToCombo() {

    String sql = """
        SELECT a.account_no      AS account_no,
               a.account_type    AS account_type,
               a.balance         AS balance,
               a.is_kh           AS is_kh
        FROM account a
        JOIN public."CUSTOMER" c
             ON a.customer_id = c."ID"
        WHERE c."UserID" = %d
        """.formatted(userid);

    var list = DBHelper.getValues(sql);
    cboAccount.removeAllItems();

    for (var row : list) {
        String no   = row.get("account_no").toString();
        String type = row.get("account_type").toString();
        double bal  = ((Number) row.get("balance")).doubleValue();
        boolean isKh = (Boolean) row.get("is_kh");   // or (boolean)

        String symbol = isKh ? "៛" : "$";
        String text = "%s - %s (%,.2f %s)".formatted(no, type, bal, symbol);

        cboAccount.addItem(text);
    }
}

       private boolean iskh;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        lblTitleGetCash = new java.awt.Label();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        cboProvider = new javax.swing.JComboBox<>();
        panel8 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        panel9 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        txtBiilingmonth = new javax.swing.JTextField();
        panel10 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        panel14 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        cboAccount = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        btndeposit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(10, 31, 57));

        lblTitleGetCash.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblTitleGetCash.setForeground(new java.awt.Color(220, 194, 154));
        lblTitleGetCash.setName(""); // NOI18N
        lblTitleGetCash.setText("Pay Electricity");

        panel2.setBackground(new java.awt.Color(10, 31, 57));
        panel2.setForeground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 194, 154));
        jLabel1.setText("Provider");

        cboProvider.setBackground(new java.awt.Color(10, 31, 57));
        cboProvider.setEditable(true);
        cboProvider.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboProvider.setForeground(new java.awt.Color(220, 194, 154));
        cboProvider.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PP", "KK", "KPS" }));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                    .addContainerGap(159, Short.MAX_VALUE)
                    .addComponent(cboProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(cboProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel8.setBackground(new java.awt.Color(10, 31, 57));
        panel8.setForeground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 194, 154));
        jLabel2.setText("Customer ID");

        txtCustomerId.setBackground(new java.awt.Color(10, 31, 57));
        txtCustomerId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCustomerId.setForeground(new java.awt.Color(220, 194, 154));
        txtCustomerId.setName(""); // NOI18N

        javax.swing.GroupLayout panel8Layout = new javax.swing.GroupLayout(panel8);
        panel8.setLayout(panel8Layout);
        panel8Layout.setHorizontalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel8Layout.setVerticalGroup(
            panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panel9.setBackground(new java.awt.Color(10, 31, 57));
        panel9.setForeground(new java.awt.Color(255, 255, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 194, 154));
        jLabel3.setText("Billing Month");

        txtBiilingmonth.setBackground(new java.awt.Color(10, 31, 57));
        txtBiilingmonth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBiilingmonth.setForeground(new java.awt.Color(220, 194, 154));
        txtBiilingmonth.setName(""); // NOI18N

        javax.swing.GroupLayout panel9Layout = new javax.swing.GroupLayout(panel9);
        panel9.setLayout(panel9Layout);
        panel9Layout.setHorizontalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBiilingmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel9Layout.setVerticalGroup(
            panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBiilingmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panel10.setBackground(new java.awt.Color(10, 31, 57));
        panel10.setForeground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(220, 194, 154));
        jLabel4.setText("Acount");

        txtAmount.setBackground(new java.awt.Color(10, 31, 57));
        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(220, 194, 154));
        txtAmount.setName(""); // NOI18N

        javax.swing.GroupLayout panel10Layout = new javax.swing.GroupLayout(panel10);
        panel10.setLayout(panel10Layout);
        panel10Layout.setHorizontalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel10Layout.setVerticalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panel14.setBackground(new java.awt.Color(10, 31, 57));
        panel14.setForeground(new java.awt.Color(255, 255, 204));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(220, 194, 154));
        jLabel5.setText("Pay From Account");

        cboAccount.setBackground(new java.awt.Color(10, 31, 57));
        cboAccount.setEditable(true);
        cboAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboAccount.setForeground(new java.awt.Color(220, 194, 154));
        cboAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setBackground(new java.awt.Color(21, 42, 66));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(220, 194, 154));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow.png"))); // NOI18N
        jButton5.setText("CanCel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btndeposit.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit.setText("Deposit");
        btndeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel14Layout = new javax.swing.GroupLayout(panel14);
        panel14.setLayout(panel14Layout);
        panel14Layout.setHorizontalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel14Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(cboAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel14Layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel14Layout.createSequentialGroup()
                                .addComponent(btndeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)))))
                .addContainerGap())
        );
        panel14Layout.setVerticalGroup(
            panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MainForm main = new MainForm(this.userid);
        main.setLocationRelativeTo(null);
        main.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btndepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositActionPerformed
   try {
    String amountText  = txtAmount.getText().trim();
    if (amountText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Amount");
        return;
    }

    String billingMonth = txtBiilingmonth.getText().trim();
    if (billingMonth.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Billing Month");
        return;
    }

    String customerIdText = txtCustomerId.getText().trim();
    if (customerIdText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter Customer ID");
        return;
    }

    Object selAccount = cboAccount.getSelectedItem();
    if (selAccount == null) {
        JOptionPane.showMessageDialog(this, "Please choose Pay From Account");
        return;
    }

    BigDecimal amount = new BigDecimal(amountText);

    String accountInfo = selAccount.toString();
    String[] parts     = accountInfo.split(" - ");
    String accountNo   = parts[0].trim();

    String sqlAcc = """
        SELECT a.id, a.balance, a.is_kh
        FROM account a
        JOIN public."CUSTOMER" c ON a.customer_id = c."ID"
        WHERE a.account_no = ?
          AND c."UserID" = ?
        """;

    var accList = DBHelper.getValues(sqlAcc, accountNo, this.userid);

    if (accList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Account not found!");
        return;
    }

    var acc = accList.get(0);
    long accountIdDb         = ((Number) acc.get("id")).longValue();
    BigDecimal balanceBefore = new BigDecimal(acc.get("balance").toString());
    boolean isKh             = (Boolean) acc.get("is_kh");

    if (balanceBefore.compareTo(amount) < 0) {
        JOptionPane.showMessageDialog(this, "Not enough balance!");
        return;
    }

    BigDecimal balanceAfter = balanceBefore.subtract(amount);

    int providerId  = 2;
    String noteText = "Pay water CID:" + customerIdText + " Month:" + billingMonth;

    String sqlBill = """
        INSERT INTO public.bill_payment(
            account_id,
            provider_id,
            customer_ref,
            bill_month,
            amount,
            is_kh,
            created_at,
            user_id,
            note
        )
        VALUES (?, ?, ?, ?, ?, ?, NOW(), ?, ?);
        """;

    int rowsBill = DBHelper.execute(
            sqlBill,
            accountIdDb,
            providerId,
            customerIdText,
            billingMonth,
            amount,
            isKh,
            this.userid,
            noteText
    );

    if (rowsBill == 0) {
        JOptionPane.showMessageDialog(this,
                "bill_payment insert failed.",
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sqlTrans = """
        INSERT INTO public.atm_transaction(
            account_id,
            user_id,
            tran_type,
            amount,
            is_kh,
            balance_before,
            balance_after,
            created_at,
            note
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, NOW(), ?);
        """;

    int rowsTrans = DBHelper.execute(
            sqlTrans,
            accountIdDb,
            this.userid,
            "WATER_PAY",
            amount,
            isKh,
            balanceBefore,
            balanceAfter,
            noteText
    );

    if (rowsTrans == 0) {
        JOptionPane.showMessageDialog(this,
                "atm_transaction insert failed.",
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sqlUpdateAcc = """
        UPDATE account
        SET balance = ?
        WHERE id = ?
        """;

    int rowsUpdate = DBHelper.execute(sqlUpdateAcc, balanceAfter, accountIdDb);

    if (rowsUpdate == 0) {
        JOptionPane.showMessageDialog(this,
                "Balance not updated in account table.",
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    JOptionPane.showMessageDialog(this,
            "Water Payment Successful!\n" +
            "Customer ID: " + customerIdText + "\n" +
            "Month: " + billingMonth + "\n" +
            "Amount: " + amount + "\n" +
            "New Balance: " + balanceAfter);

    txtAmount.setText("");
    txtBiilingmonth.setText("");
    txtCustomerId.setText("");

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    e.printStackTrace();
}


    }//GEN-LAST:event_btndepositActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiPayWater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiPayWater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiPayWater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiPayWater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiPayWater().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeposit;
    private javax.swing.JComboBox<String> cboAccount;
    private javax.swing.JComboBox<String> cboProvider;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Label lblTitleGetCash;
    private java.awt.Panel panel1;
    private java.awt.Panel panel10;
    private java.awt.Panel panel14;
    private java.awt.Panel panel2;
    private java.awt.Panel panel8;
    private java.awt.Panel panel9;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBiilingmonth;
    private javax.swing.JTextField txtCustomerId;
    // End of variables declaration//GEN-END:variables
}
