/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

import com.mycompany.atm.transaction.system.DB.DBHelper;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class guipayPhoneTop_up extends javax.swing.JFrame {


    private int currentUserId;
    public guipayPhoneTop_up(int currentUserId_) {
        initComponents();
        this.currentUserId = currentUserId_;
        this.loadAccountsToCombo();
    } 
    public guipayPhoneTop_up() {
     
    }
       private boolean iskh;
   private void loadAccountsToCombo() {
    String sql = """
        SELECT "AccountNo", "AccountType", "Balance($)", "isKh"
        FROM public."CUSTOMER"
        WHERE "UserID" = %d
        """.formatted(currentUserId);

    var list = DBHelper.getValues(sql);
    cboAccount.removeAllItems();

    for (var row : list) {
        String no = row.get("AccountNo").toString();
        String type = row.get("AccountType").toString();
        double bal  = ((Number)row.get("Balance($)")).doubleValue();
         this.iskh = (boolean)row.get("isKh");
        String symbol = this.iskh ? "៛" : "$";

        String text = "%s - %s (%,.2f %s)".formatted(no, type, bal, symbol);
        cboAccount.addItem(text);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jOptionPane1 = new javax.swing.JOptionPane();
        panel1 = new java.awt.Panel();
        lblTitleGetCash = new java.awt.Label();
        btnGetCash = new java.awt.Button();
        btnGetCash1 = new java.awt.Button();
        cboAccount = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPhoneAmount = new javax.swing.JTextField();
        btndeposit = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(10, 31, 57));

        lblTitleGetCash.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        lblTitleGetCash.setForeground(new java.awt.Color(220, 194, 154));
        lblTitleGetCash.setName(""); // NOI18N
        lblTitleGetCash.setText("Pay Mobile Phone");

        btnGetCash.setBackground(new java.awt.Color(10, 31, 57));
        btnGetCash.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGetCash.setForeground(new java.awt.Color(220, 194, 154));
        btnGetCash.setLabel("Payment");
        btnGetCash.setName(""); // NOI18N
        btnGetCash.setPreferredSize(new java.awt.Dimension(100, 70));
        btnGetCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCashActionPerformed(evt);
            }
        });

        btnGetCash1.setBackground(new java.awt.Color(10, 31, 57));
        btnGetCash1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnGetCash1.setForeground(new java.awt.Color(220, 194, 154));
        btnGetCash1.setLabel("Cancel");
        btnGetCash1.setPreferredSize(new java.awt.Dimension(100, 70));
        btnGetCash1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCash1ActionPerformed(evt);
            }
        });

        cboAccount.setBackground(new java.awt.Color(10, 31, 57));
        cboAccount.setEditable(true);
        cboAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboAccount.setForeground(new java.awt.Color(220, 194, 154));
        cboAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 194, 154));
        jLabel1.setText("From Account");

        txtPhoneNumber.setBackground(new java.awt.Color(10, 31, 57));
        txtPhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPhoneNumber.setForeground(new java.awt.Color(220, 194, 154));
        txtPhoneNumber.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 194, 154));
        jLabel2.setText("Phone Number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 194, 154));
        jLabel3.setText("$");

        txtPhoneAmount.setBackground(new java.awt.Color(10, 31, 57));
        txtPhoneAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPhoneAmount.setForeground(new java.awt.Color(220, 194, 154));
        txtPhoneAmount.setName(""); // NOI18N

        btndeposit.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit.setText("Deposit");
        btndeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(21, 42, 66));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(220, 194, 154));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/arrow.png"))); // NOI18N
        jButton5.setText("CanCel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(cboAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addComponent(btnGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGetCash1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPhoneAmount)))
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btndeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhoneAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnGetCash1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeposit))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCashActionPerformed
     



        
        
    }//GEN-LAST:event_btnGetCashActionPerformed

    private void btnGetCash1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCash1ActionPerformed
       this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetCash1ActionPerformed

    private void btndepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositActionPerformed
      try {
    // 1. Collect UI values
    String accountInfo = cboAccount.getSelectedItem().toString();
    String phone       = txtPhoneNumber.getText().trim();
    String amtStr      = txtPhoneAmount.getText().trim();

    if (accountInfo.isEmpty() || phone.isEmpty() || amtStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields!");
        return;
    }

    double amount = Double.parseDouble(amtStr);

    // From: 0011110105 - CHECKING (3,590,865.00 ៛)
    String[] parts   = accountInfo.split(" - ");
    String accountNo = parts[0].trim();

    // 2. Load account balance from CUSTOMER
    String sqlAcc = """
        SELECT "ID", "Balance($)" AS balance
        FROM "CUSTOMER"
        WHERE "AccountNo" = ?
        """;

    var accList = DBHelper.getValues(sqlAcc, accountNo);

    if (accList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Account not found!");
        return;
    }

    var acc = accList.get(0);
    long customerId      = ((Number) acc.get("ID")).longValue();
    double balanceBefore = ((Number) acc.get("balance")).doubleValue();

    if (balanceBefore < amount) {
        JOptionPane.showMessageDialog(this, "Insufficient balance!");
        return;
    }

    double balanceAfter = balanceBefore - amount;

    // 3. Detect operator
    String operator = "Unknown";
    if (phone.startsWith("096") || phone.startsWith("076") || phone.startsWith("086"))
        operator = "Cellcard";
    else if (phone.startsWith("010") || phone.startsWith("093") || phone.startsWith("098"))
        operator = "Smart";
    else if (phone.startsWith("097") || phone.startsWith("088"))
        operator = "Metfone";

    // 4. Insert into TopUp
    String sqlTopUp = """
        INSERT INTO public."TopUp"(
            "UserID",
            "AccountNo",
            "PhoneNumber",
            "Operator",
            "Amount",
            "CreatedAt"
        )
        VALUES (?, ?, ?, ?, ?, NOW())
        RETURNING "TopUpID";
        """;

    Object topUpIdObj = DBHelper.executeScalar(
            sqlTopUp,
            this.currentUserId,
            accountNo,
            phone,
            operator,
            amount
    );
    long topUpId = topUpIdObj == null ? 0L : ((Number) topUpIdObj).longValue();

    if (topUpId == 0L) {
        JOptionPane.showMessageDialog(this,
                "❌ TopUp insert failed (TopUpID = 0).",
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 5. Insert into atm_transaction (ledger)
    String sqlTrans = """
        INSERT INTO public.atm_transaction(
            account_id,
            user_id,
            tran_type,
            amount,
            is_kh,
            balance_before,
            balance_after,
            created_at,
            note
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, NOW(), ?);
        """;

    boolean isKh = true; 

    int rowsTrans = DBHelper.execute(sqlTrans,
            customerId,
            this.currentUserId,
            "MOBILE_TOPUP",
            amount,
            isKh,
            balanceBefore,
            balanceAfter,
            "Mobile top-up " + operator + " " + phone
    );

    if (rowsTrans == 0) {
        JOptionPane.showMessageDialog(this,
                "❌ atm_transaction insert failed (rows = 0).\nPlease check console / DB error.",
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 6. Update CUSTOMER balance
    String sqlUpdateAcc = """
        UPDATE "CUSTOMER"
        SET "Balance($)" = ?
        WHERE "ID" = ?
        """;
    int rowsUpdate = DBHelper.execute(sqlUpdateAcc, balanceAfter, customerId);

    if (rowsUpdate == 0) {
        JOptionPane.showMessageDialog(this,
                "❌ Balance not updated in CUSTOMER table.",
                "ERROR",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 7. Success message — only if all 3 steps OK
    JOptionPane.showMessageDialog(this,
            "Top-up Successful!\n" +
            "Phone: " + phone + "\n" +
            "Amount: " + amount + "\n" +
            "Operator: " + operator + "\n" +
            "New Balance: " + balanceAfter);

    txtPhoneNumber.setText("");
    txtPhoneAmount.setText("");

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    e.printStackTrace();
}
    }//GEN-LAST:event_btndepositActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MainForm main = new MainForm(this.currentUserId);
        main.setLocationRelativeTo(null);
        main.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guipayPhoneTop_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guipayPhoneTop_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guipayPhoneTop_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guipayPhoneTop_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guipayPhoneTop_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnGetCash;
    private java.awt.Button btnGetCash1;
    private javax.swing.JButton btndeposit;
    private javax.swing.JComboBox<String> cboAccount;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.Label lblTitleGetCash;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtPhoneAmount;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
