/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

import com.mycompany.atm.transaction.system.DB.DBHelper;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author HQ
 */
public class guiReportByAccout extends javax.swing.JFrame {

    /**
     * Creates new form guiReportByAccout
     */
    public guiReportByAccout() {
        initComponents();
        this.loadingAccount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        btnPriview = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        label1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        label1.setText("ATM System ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setText("Account");

        btnPriview.setText("Priview");
        btnPriview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriviewActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                comboBoxKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnPriview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPriview)
                    .addComponent(btnCancel))
                .addGap(0, 267, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPriviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriviewActionPerformed
        try {
            // ១. ទាញយក Connection
            java.sql.Connection conn = com.mycompany.atm.transaction.system.DB.dbcontextion.getConnection();

            // ២. រៀបចំ Parameter (ប្រើ sql.Date ដើម្បីឱ្យច្បាស់លាស់ជាមួយ Database)
            java.util.HashMap<String, Object> params = new java.util.HashMap<>();
//            params.put("DATE_FROM", new java.sql.Date(pickerFrom.getDate().getTime()));
//            params.put("DATE_TO", new java.sql.Date(pickerTo.getDate().getTime()));

            InputStream jrxml = getClass().getResourceAsStream("/Suspicious_Transaction_Report.jrxml");

            JasperReport report = JasperCompileManager.compileReport(jrxml);

       
            
            
            
            
            JasperPrint print = JasperFillManager.fillReport(report, params, conn);

            JasperViewer.viewReport(print, false);

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "មានបញ្ហា៖ " + e.getMessage());
        }
    }//GEN-LAST:event_btnPriviewActionPerformed
private List<String> accountList = new ArrayList<>();

private void loadingAccount() {
    String sql = "SELECT account_no FROM account";
    
    // ប្រើ DBHelper ដើម្បីទាញយកទិន្នន័យជា ArrayList<HashMap>
    ArrayList<HashMap<String, Object>> data = DBHelper.getValues(sql);
    
    accountList.clear();
    comboBox.removeAllItems();

    for (HashMap<String, Object> row : data) {
        String acc = row.get("account_no").toString();
        accountList.add(acc);
        comboBox.addItem(acc);
    }
}

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void comboBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBoxKeyReleased
        // TODO add your handling code here:
        // ដាក់កូដនេះក្នុង Constructor ឬកន្លែង Initialize components
comboBox.setEditable(true); // ត្រូវតែដាក់ឱ្យវាអាចវាយអក្សរបាន (Editable)

JTextField editor = (JTextField) comboBox.getEditor().getEditorComponent();

editor.addKeyListener(new KeyAdapter() {
    @Override
    public void keyReleased(KeyEvent e) {
        // ចាប់យកអក្សរដែលកំពុងវាយ
        String text = editor.getText();
        
        // កុំឱ្យវា Search នៅពេលចុច Arrow Keys (ឡើងលើ ចុះក្រោម)
        if (e.getKeyCode() != KeyEvent.VK_UP && e.getKeyCode() != KeyEvent.VK_DOWN && e.getKeyCode() != KeyEvent.VK_ENTER) {
            searchAccount(text);
            editor.setText(text); // រក្សាទុកអក្សរដែលកំពុងវាយ កុំឱ្យវាបាត់
        }
    }
});
    }//GEN-LAST:event_comboBoxKeyReleased
private Connection conn;
public void searchAccount(String text) {
    // លុបទិន្នន័យចាស់ក្នុង ComboBox ចេញសិន
    comboBox.removeAllItems();
    
    // បើប្រអប់ទទេ ឱ្យវាបង្ហាញទាំងអស់ឡើងវិញ
    if (text.isEmpty()) {
        for (String acc : accountList) {
            comboBox.addItem(acc);
        }
    } else {
        // បើមានការវាយអក្សរ ឱ្យវា Filter យកតែពាក្យដែលផ្ដើមដោយអក្សរនោះ (StartsWith)
        for (String acc : accountList) {
            if (acc.toLowerCase().startsWith(text.toLowerCase())) {
                comboBox.addItem(acc);
            }
        }
    }
    
    // បើក Dropdown ឱ្យវាបង្ហាញលទ្ធផល
    comboBox.setPopupVisible(true);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the NOn the third day, called Virak Loeung Sak,
people do water blessing.
They pour water on Buddha statues and elders
to wash away bad luck and receive blessings.
imbus look a//    private void loadingAccount(){
//    String sql = "SELECT account_no FROM account";
//
//
//       try {
//                var list = DBHelper.getValues(sql);
//            comboBox.removeAllItems();
//
//            for (var row : list) {
//                String no   = row.get("account_no").toString();
//
//                comboBox.addItem(no);
//            }
//    
//
//       } catch (Exception e) {
//           e.printStackTrace();
//       }
//
//    }nd feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiReportByAccout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiReportByAccout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiReportByAccout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiReportByAccout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiReportByAccout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPriview;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
