/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

import com.mycompany.atm.transaction.system.DB.DBHelper;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HQ
 */
public class guitrasation extends javax.swing.JPanel {

    /**
     * Creates new form DashBoardPanel_
     */
    public guitrasation() {
        initComponents();
    }

    
          public guitrasation(int userid , boolean iskh) {
                initComponents();
                     setKhmerFont(this);
                 if(iskh) {
                iskh = false;

                        setKh();

                        } else {
                            iskh = true;    setEng();
                        }
                 this.loadType();
                 this.loadingtransation();
    }
 public void setKh() {
    lblFrom.setText("ពីថ្ងៃ");
    lblTo.setText("ដល់ថ្ងៃ");
    txttpye.setBorder(javax.swing.BorderFactory.createTitledBorder("ប្រភេទ"));
    btnfilter.setText("ត្រង់");
    btnresent.setText("កំណត់ឡើងវិញ");

    dtpdatefrom.setBorder(javax.swing.BorderFactory.createTitledBorder("ថ្ងៃទីចាប់ផ្តើម"));
    dptdateto.setBorder(javax.swing.BorderFactory.createTitledBorder("កាលបរិច្ឆេទបញ្ចប់"));
}

public void setEng() {
    lblFrom.setText("From");
    lblTo.setText("To");
    txttpye.setBorder(javax.swing.BorderFactory.createTitledBorder("Type"));
    btnfilter.setText("Filter");
    btnresent.setText("Reset");

    dtpdatefrom.setBorder(javax.swing.BorderFactory.createTitledBorder("Start Date"));
    dptdateto.setBorder(javax.swing.BorderFactory.createTitledBorder("End Date"));
}


private void setKhmerFont(java.awt.Component component) {
    java.awt.Font current = component.getFont();
    java.awt.Font khFont = new java.awt.Font("Khmer OS Battambang", current.getStyle(), current.getSize());
    component.setFont(khFont);

    if (component instanceof java.awt.Container) {
        for (java.awt.Component child : ((java.awt.Container) component).getComponents()) {
            setKhmerFont(child);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdd2 = new javax.swing.JButton();
        btnClose  = new javax.swing.JButton();
        btnAdd3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblFrom = new javax.swing.JLabel();
        dtpdatefrom = new com.toedter.calendar.JDateChooser();
        dptdateto = new com.toedter.calendar.JDateChooser();
        lblTo = new javax.swing.JLabel();
        cboteyps = new javax.swing.JComboBox<>();
        txttpye = new javax.swing.JTextField();
        btnfilter = new javax.swing.JButton();
        btnresent = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaction = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("SimSun", 0, 36)); // NOI18N
        jLabel2.setText("ATM SU35 System ");

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAdd2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd2.setText("Export To Excel");
        btnAdd2.setToolTipText("");
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Segoe UI",0,18));
        btnClose.setText("Close");
        btnClose.setToolTipText("");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclassActionPerformed(evt);
            }
        });




        btnAdd3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd3.setText("Close");
        btnAdd3.setToolTipText("");
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblFrom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFrom.setText("From");

        dtpdatefrom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        dptdateto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTo.setText("TO");

        btnfilter.setText("Filter");
        btnfilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfilterActionPerformed(evt);
            }
        });

        btnresent.setText("Resent");
        btnresent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblFrom)
                .addGap(18, 18, 18)
                .addComponent(dtpdatefrom, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblTo)
                .addGap(18, 18, 18)
                .addComponent(dptdateto, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboteyps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txttpye, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnfilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnresent)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblFrom)
                    .addComponent(dtpdatefrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dptdateto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTo)
                    .addComponent(cboteyps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttpye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfilter)
                    .addComponent(btnresent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 91));

        tblTransaction.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Date/Time", "Customer Name ", "Account No", "Type ", "Amount", "Currency", "Created By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTransaction);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd2)
                .addGap(18, 18, 18)
                .addComponent(btnAdd3)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd2)
                    .addComponent(btnAdd3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private  void btnclassActionPerformed(java.awt.event.ActionEvent evt){

    }
    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        // TODO add your handling code here:
        
                    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Save Transactions");
    chooser.setSelectedFile(new File("transactions.csv")); // default name

    int result = chooser.showSaveDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        exportTableToExcel(tblTransaction, file);
    }
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
           this.hide();
    }//GEN-LAST:event_btnAdd3ActionPerformed
             private void loadType() {
    cboteyps.removeAllItems();
    
    cboteyps.addItem("All");
    cboteyps.addItem("DEPOSIT");
    cboteyps.addItem("GET_CASH");
    cboteyps.addItem("MOBILE_TOPUP");
    cboteyps.addItem("ELECTRICITY_PAY");
    cboteyps.addItem("WATER_PAY");
}
    private void btnfilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfilterActionPerformed
    
                 try {

    // --- Get UI values ---
    java.util.Date fromUtil = dtpdatefrom.getDate();
    java.util.Date toUtil   = dptdateto.getDate();

    if (fromUtil == null || toUtil == null) {
        JOptionPane.showMessageDialog(this, "Please select From / To date");
        return;
    }

    java.sql.Timestamp fromDate = new java.sql.Timestamp(fromUtil.getTime());
    java.sql.Timestamp toDate   = new java.sql.Timestamp(toUtil.getTime());

    Object sel = cboteyps.getSelectedItem();
    String type = (sel == null) ? "" : sel.toString().trim();

    String search = txttpye.getText().trim();

    // --- Build SQL with ? parameters ---
    String sql = """
        SELECT  t.id AS transaction_id,
                t.created_at,
                c."CustomerName" AS customer_name,
                a.account_no,
                t.tran_type AS type,
                t.amount,
                CASE WHEN a.is_kh THEN 'KHR' ELSE 'USD' END AS currency,
                u.username
        FROM public.atm_transaction t
        JOIN public.account a      ON t.account_id = a.id
        JOIN public."CUSTOMER" c   ON a.customer_id = c."ID"
        JOIN public.users u        ON t.user_id = u.userid
        WHERE t.created_at BETWEEN ? AND ?
        """;

    // collect parameters in order
    java.util.List<Object> params = new java.util.ArrayList<>();
    params.add(fromDate);
    params.add(toDate);

    // If type selected and not All
    if (!type.equalsIgnoreCase("All") && !type.isEmpty()) {
        sql += " AND t.tran_type = ? ";
        params.add(type);
    }

    // If search text
    if (!search.isEmpty()) {
        sql += " AND (c.\"CustomerName\" ILIKE ? OR a.account_no ILIKE ?) ";
        String like = "%" + search + "%";
        params.add(like);
        params.add(like);
    }

    sql += " ORDER BY t.created_at DESC ";

    // --- Call DBHelper ---
    ArrayList<HashMap<String, Object>> rows =
            DBHelper.getValues(sql, params.toArray());

    // --- Load into JTable ---
    DefaultTableModel model = (DefaultTableModel) tblTransaction.getModel();
    model.setRowCount(0);

    for (HashMap<String, Object> row : rows) {
        model.addRow(new Object[]{
            row.get("transaction_id"),
            row.get("created_at"),
            row.get("customer_name"),
            row.get("account_no"),
            row.get("type"),
            row.get("amount"),
            row.get("currency"),
            row.get("username")
        });
    }

} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error Filter: " + ex.getMessage());
}


    }//GEN-LAST:event_btnfilterActionPerformed
private void exportTableToExcel(JTable table, File file) {
    try (BufferedWriter bw = new BufferedWriter(new FileWriter(file))) {

        TableModel model = table.getModel();

        // ---- header (column names)
        for (int i = 0; i < model.getColumnCount(); i++) {
            bw.write(model.getColumnName(i));
            if (i < model.getColumnCount() - 1) {
                bw.write(",");
            }
        }
        bw.newLine();

        // ---- data rows
        for (int row = 0; row < model.getRowCount(); row++) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                Object value = model.getValueAt(row, col);
                bw.write(value == null ? "" : value.toString());
                if (col < model.getColumnCount() - 1) {
                    bw.write(",");
                }
            }
            bw.newLine();
        }

        JOptionPane.showMessageDialog(this,
                "Export completed!",
                "Export",
                JOptionPane.INFORMATION_MESSAGE);

    } catch (IOException ex) {
        JOptionPane.showMessageDialog(this,
                "Error: " + ex.getMessage(),
                "Export error",
                JOptionPane.ERROR_MESSAGE);
    }
}

    private void btnresentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresentActionPerformed
    txttpye.setText("");
    cboteyps.setSelectedIndex(0);
    loadingtransation();
    }//GEN-LAST:event_btnresentActionPerformed
private void loadingtransation() {
    try {
        String sql = """
            SELECT  t.id AS transaction_id,
                    t.created_at,
                    c."CustomerName" AS customer_name,
                    a.account_no,
                    t.tran_type AS type,
                    t.amount,
                    CASE WHEN a.is_kh THEN 'KHR' ELSE 'USD' END AS currency,
                    u.username
            FROM public.atm_transaction t
            JOIN public.account a      ON t.account_id = a.id
            JOIN public."CUSTOMER" c   ON a.customer_id = c."ID"
            JOIN public.users u        ON t.user_id = u.userid
            ORDER BY t.created_at DESC
            """;

        ArrayList<HashMap<String, Object>> rows = DBHelper.getValues(sql);

        DefaultTableModel model = (DefaultTableModel) tblTransaction.getModel();
        model.setRowCount(0);

        for (HashMap<String, Object> row : rows) {
            model.addRow(new Object[]{
                row.get("transaction_id"),
                row.get("created_at"),
                row.get("customer_name"),
                row.get("account_no"),
                row.get("type"),
                row.get("amount"),
                row.get("currency"),
                row.get("username")
            });
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading transactions: " + ex.getMessage());
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnfilter;
    private javax.swing.JButton btnresent;
    private javax.swing.JComboBox<String> cboteyps;
    private com.toedter.calendar.JDateChooser dptdateto;
    private com.toedter.calendar.JDateChooser dtpdatefrom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTable tblTransaction;
    private javax.swing.JTextField txttpye;
    private javax.swing.JButton btnClose;
    // End of variables declaration//GEN-END:variables
}
