/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.atm.transaction.system.ui;

import com.mycompany.atm.transaction.system.DB.DBHelper;
import com.mycompany.atm.transaction.system.DB.setKhmerFont;

import javax.swing.JOptionPane;
import java.awt.*;

/**
 *
 * @author HQ
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private  setKhmerFont font = new setKhmerFont();
    private int currentUserId;
    public MainForm(){
             initComponents();
    }

    public boolean iskh;
    public MainForm(int userId,boolean iskh) {
    initComponents();
    this.font.setFont(this);
    this.currentUserId = userId;
    this.iskh = iskh;
    this.loadTotalBalances();
    if(iskh){
        getkh();
    }else{
        geteng();
    }
        
  
        
    }// Function to set UI to Khmer

    private void getkh() {

        lblTotalBalance.setText("សមតុល្យសរុប");
        btnGetCash.setText("ដកប្រាក់");
        btndeposit.setText("ដាក់ប្រាក់");
        btnCard.setText("កាតឥណទាន");
        btnPayments.setText("ការទូទាត់");
        btnsetting.setText("ការកំណត់គណនី");
        btnother.setText("ផ្សេងៗ");
    }

    // Function to set UI to English
    private void geteng() {

        lblTotalBalance.setText("Total Balance");
        btnGetCash.setText("Get Cash");
        btndeposit.setText("Deposit");
        btnCard.setText("Credit Card");
        btnPayments.setText("Payments");
        btnsetting.setText("Account Settings");
        btnother.setText("Other");
    }
  private void loadTotalBalances() {

    // KHR
    String sqlKhr = """
        SELECT COALESCE(SUM(a.balance), 0)
        FROM account a
        JOIN public."CUSTOMER" c
             ON a.customer_id = c."ID"
        WHERE c."UserID" = %d
          AND a.is_kh = TRUE
        """.formatted(currentUserId);

    Object resKhr = DBHelper.getSingleValue(sqlKhr);
    double totalKhr = (resKhr instanceof Number) ? ((Number) resKhr).doubleValue() : 0.0;

    // USD
    String sqlUsd = """
        SELECT COALESCE(SUM(a.balance), 0)
        FROM account a
        JOIN public."CUSTOMER" c
             ON a.customer_id = c."ID"
        WHERE c."UserID" = %d
          AND a.is_kh = FALSE
        """.formatted(currentUserId);

    Object resUsd = DBHelper.getSingleValue(sqlUsd);
    double totalUsd = (resUsd instanceof Number) ? ((Number) resUsd).doubleValue() : 0.0;

     lblbalandkh.setText(String.format("%,.2f ៛", totalKhr));
    lblBalnceus.setText(String.format("%,.2f $", totalUsd));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        popupMenu1 = new java.awt.PopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnGetCash = new javax.swing.JButton();
        btndeposit = new javax.swing.JButton();
        btnCard = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnsetting = new javax.swing.JButton();
        btnother = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        lblBalnceus = new java.awt.Label();
        lblTotalBalance = new java.awt.Label();
        lblbalandkh = new java.awt.Label();
        btnhide = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Get Cash");

        jButton7.setBackground(new java.awt.Color(0, 102, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Get Cash");

        jButton8.setBackground(new java.awt.Color(0, 102, 255));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Get Cash");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATM");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel4.setBackground(new java.awt.Color(10, 31, 57));

        btnGetCash.setBackground(new java.awt.Color(21, 42, 66));
        btnGetCash.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGetCash.setForeground(new java.awt.Color(220, 194, 154));
        btnGetCash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/get-money.png"))); // NOI18N
        btnGetCash.setText("Get Cash");
        btnGetCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCashActionPerformed(evt);
            }
        });

        btndeposit.setBackground(new java.awt.Color(21, 42, 66));
        btndeposit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btndeposit.setForeground(new java.awt.Color(220, 194, 154));
        btndeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/deposit.png"))); // NOI18N
        btndeposit.setText("Deposit");
        btndeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositActionPerformed(evt);
            }
        });

        btnCard.setBackground(new java.awt.Color(21, 42, 66));
        btnCard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCard.setForeground(new java.awt.Color(220, 194, 154));
        btnCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/atm-card (1).png"))); // NOI18N
        btnCard.setText("Credit Card");
        btnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardActionPerformed(evt);
            }
        });

        btnPayments.setBackground(new java.awt.Color(21, 42, 66));
        btnPayments.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPayments.setForeground(new java.awt.Color(220, 194, 154));
        btnPayments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/payment-method (1).png"))); // NOI18N
        btnPayments.setText("Payments");
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });

        btnsetting.setBackground(new java.awt.Color(21, 42, 66));
        btnsetting.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsetting.setForeground(new java.awt.Color(220, 194, 154));
        btnsetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account-settings.png"))); // NOI18N
        btnsetting.setText("Account Settings");
        btnsetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsettingActionPerformed(evt);
            }
        });

        btnother.setBackground(new java.awt.Color(223, 204, 176));
        btnother.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnother.setText("Other");

        label1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(220, 194, 154));
        label1.setName(""); // NOI18N
        label1.setText("ATM SYSTEM");

        jPanel2.setBackground(new java.awt.Color(21, 42, 66));

        lblBalnceus.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblBalnceus.setForeground(new java.awt.Color(220, 194, 154));
        lblBalnceus.setName(""); // NOI18N
        lblBalnceus.setText("00.00​ $ ");

        lblTotalBalance.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTotalBalance.setForeground(new java.awt.Color(220, 194, 154));
        lblTotalBalance.setName(""); // NOI18N
        lblTotalBalance.setText("Total Balance");

        lblbalandkh.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblbalandkh.setForeground(new java.awt.Color(220, 194, 154));
        lblbalandkh.setName(""); // NOI18N
        lblbalandkh.setText("00.00 ");

        btnhide.setBackground(new java.awt.Color(21, 42, 66));
        btnhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhideActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(21, 42, 66));
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(220, 194, 154));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/my-account.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblbalandkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBalnceus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTotalBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnhide, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(lblbalandkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBalnceus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnsetting, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                                .addComponent(btnPayments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(6, 6, 6)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnother, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCard, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addComponent(btnGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btndeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetCash, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCard, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPayments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsetting, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnother, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositActionPerformed
       guiDeposit getCash = new guiDeposit(this.currentUserId);
    getCash.setLocationRelativeTo(this); 
    getCash.setVisible(true);
     this.dispose(); 
    }//GEN-LAST:event_btndepositActionPerformed

    private void btnGetCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCashActionPerformed
                
                               

    frmGetCash getCash = new frmGetCash(this.currentUserId,iskh);
    getCash.setLocationRelativeTo(this); // center relative to main form
    getCash.setVisible(true);
     this.dispose(); 

    }//GEN-LAST:event_btnGetCashActionPerformed

    private void btnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardActionPerformed
        // TODO add your handling code here:
        
        
                    guiCreateCard getCash = new guiCreateCard(this.currentUserId,iskh);
    getCash.setLocationRelativeTo(this); // center relative to main form
    getCash.setVisible(true);
     this.dispose(); 
    }//GEN-LAST:event_btnCardActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         guiAddAccount getCash = new guiAddAccount(this.currentUserId);
    getCash.setLocationRelativeTo(this); // center relative to main form
    getCash.setVisible(true);
     this.dispose(); 
    }//GEN-LAST:event_jButton11ActionPerformed
  public boolean isBalanceHidden =false;
    private void btnhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhideActionPerformed
 this.isBalanceHidden = !this.isBalanceHidden;

    if (this.isBalanceHidden) {
        // hide balances
        lblbalandkh.setText("••••••••• ៛");
        lblBalnceus.setText("••••••••• $");

        // use icon from /icon folder inside project
        btnhide.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/icon/hide.png")));
    } else {
        // show balances again
        loadTotalBalances();

        btnhide.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/icon/view.png")));
    }
    }//GEN-LAST:event_btnhideActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed

    guiPayment getCash = new guiPayment(this.currentUserId,iskh);
    getCash.setLocationRelativeTo(this); 
    getCash.setVisible(true);
     this.dispose(); 
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnsettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsettingActionPerformed
        // TODO add your handling code here:guiAccouontSetting
    guiAccouontSetting getCash = new guiAccouontSetting(this.currentUserId);
    getCash.setLocationRelativeTo(this); 
    getCash.setVisible(true);
     this.dispose(); 
    }//GEN-LAST:event_btnsettingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCard;
    private javax.swing.JButton btnGetCash;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btndeposit;
    private javax.swing.JButton btnhide;
    private javax.swing.JButton btnother;
    private javax.swing.JButton btnsetting;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private java.awt.Label label1;
    private java.awt.Label lblBalnceus;
    private java.awt.Label lblTotalBalance;
    private java.awt.Label lblbalandkh;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}